# Generated by Django 3.2.16 on 2023-06-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20230614_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
