# Generated by Django 3.2.16 on 2024-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_auto_20230615_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
